// MUTATIONS
const SET_STATUS_MODEL_DONATION = "Other/SET_STATUS_MODEL_DONATION";
const SET_TOGGLE_NOTIFI = "Other/SET_TOGGLE_NOTIFI";
const SET_ALERT = "Other/SET_ALERT";
const SET_USER_DATA = "Auth/SET_DATA_USER";
const CLEAR_USER_DATA = "Auth/CLEAR_USER_DATA";
const TOGGLE_CONFIRM_ALERT = "Other/TOGGLE_CONFIRM_ALERT";
const SET_CONFIRM_ALERT = "Other/SET_CONFIRM_ALERT";
const SET_ABOUT_SITE = "Pages/SET_ABOUT_SITE";
const SET_TERMS = "Pages/SET_TERMS";
const SET_DONATIONS_SHOW = "Pages/SET_DONATIONS_SHOW";
const SET_DATA_MODEL = "Pages/SET_DATA_MODEL";
// GETTERS
const GET_TOGGLE_NOTIFI = "Other/GET_TOGGLE_NOTIFI";
const GET_STATUS_MODEL_DONATION = "Other/GET_STATUS_MODEL_DONATION";
const GET_ALERT = "Other/GET_ALERT";
const GET_STATUS_CONFIRM_ALERT = "Other/GET_STATUS_CONFIRM_ALERT";
const GET_ABOUT_SITE = "Pages/GET_ABOUT_SITE";
const GET_TERMS = "Pages/GET_TERMS";
const GET_DONATIONS_SHOW = "Pages/GET_DONATIONS_SHOW";
const GET_DATA_MODEL = "Pages/GET_DATA_MODEL";
// ACTIONS
const REGISTER = "Auth/REGISTER";
const SIGN_IN = "Auth/SIGN_IN";
const SIGN_OUT = "Auth/SIGN_OUT";
const ABOUT_SITE = "Pages/ABOUT_SITE";
const TERMS = "Pages/TERMS";
const DONATIONS_SHOW = "Pages/DONATIONS_SHOW";
const DONATE = "Pages/DONATE";
//
export {
  SET_STATUS_MODEL_DONATION,
  SET_TOGGLE_NOTIFI,
  SET_ALERT,
  SET_USER_DATA,
  TOGGLE_CONFIRM_ALERT,
  SET_CONFIRM_ALERT,
  SET_ABOUT_SITE,
  SET_TERMS,
  SET_DONATIONS_SHOW,
  SET_DATA_MODEL,
  CLEAR_USER_DATA,
  GET_TOGGLE_NOTIFI,
  GET_STATUS_MODEL_DONATION,
  GET_ALERT,
  GET_STATUS_CONFIRM_ALERT,
  GET_ABOUT_SITE,
  GET_TERMS,
  GET_DONATIONS_SHOW,
  GET_DATA_MODEL,
  REGISTER,
  SIGN_IN,
  SIGN_OUT,
  ABOUT_SITE,
  TERMS,
  DONATIONS_SHOW,
  DONATE,
};
