// MUTATIONS
const SET_STATUS_MODEL_DONATION = "index/SET_STATUS_MODEL_DONATION";
const SET_TOGGLE_NOTIFI = "index/SET_TOGGLE_NOTIFI";
const SET_ALERT = "index/SET_ALERT";
const SET_USER_DATA = "Auth/SET_DATA_USER";
const CLEAR_USER_DATA = "Auth/CLEAR_USER_DATA";
const TOGGLE_CONFIRM_ALERT = "index/TOGGLE_CONFIRM_ALERT";
const SET_CONFIRM_ALERT = "index/SET_CONFIRM_ALERT";
const SET_ABOUT_SITE = "Pages/SET_ABOUT_SITE";
const SET_TERMS = "Pages/SET_TERMS";
// GETTERS
const GET_TOGGLE_NOTIFI = "index/GET_TOGGLE_NOTIFI";
const GET_STATUS_MODEL_DONATION = "index/GET_STATUS_MODEL_DONATION";
const GET_ALERT = "index/GET_ALERT";
const GET_STATUS_CONFIRM_ALERT = "index/GET_STATUS_CONFIRM_ALERT";
const GET_ABOUT_SITE = "Pages/GET_ABOUT_SITE";
const GET_TERMS = "Pages/GET_TERMS";
// ACTIONS
const REGISTER = "Auth/REGISTER";
const SIGN_IN = "Auth/SIGN_IN";
const SIGN_OUT = "Auth/SIGN_OUT";
const ABOUT_SITE = "Pages/ABOUT_SITE";
const TERMS = "Pages/TERMS";
//
export {
  SET_STATUS_MODEL_DONATION,
  SET_TOGGLE_NOTIFI,
  SET_ALERT,
  SET_USER_DATA,
  TOGGLE_CONFIRM_ALERT,
  SET_CONFIRM_ALERT,
  SET_ABOUT_SITE,
  SET_TERMS,
  CLEAR_USER_DATA,
  GET_TOGGLE_NOTIFI,
  GET_STATUS_MODEL_DONATION,
  GET_ALERT,
  GET_STATUS_CONFIRM_ALERT,
  GET_ABOUT_SITE,
  GET_TERMS,
  REGISTER,
  SIGN_IN,
  SIGN_OUT,
  ABOUT_SITE,
  TERMS,
};
