// MUTATIONS
const SET_STATUS_MODEL_DONATION = "index/SET_STATUS_MODEL_DONATION";
const SET_TOGGLE_NOTIFI = "index/SET_TOGGLE_NOTIFI";
const SET_ALERT = "index/SET_ALERT";
// GETTERS
const GET_TOGGLE_NOTIFI = "index/GET_TOGGLE_NOTIFI";
const GET_STATUS_MODEL_DONATION = "index/GET_STATUS_MODEL_DONATION";
const GET_ALERT = "index/GET_ALERT";
// ACTIONS
const REGISTER = "index/REGISTER";
const SIGN_IN = "index/SIGN_IN";
//
export {
  SET_STATUS_MODEL_DONATION,
  SET_TOGGLE_NOTIFI,
  SET_ALERT,
  GET_TOGGLE_NOTIFI,
  GET_STATUS_MODEL_DONATION,
  GET_ALERT,
  REGISTER,
  SIGN_IN,
};
